import * as T from '../arcade/vendor/three.module.min.js';
import {Atmosphere} from './atmosphere.js?v=20261007a';
import {buildWorld,heightAt,BEACONS,GATE} from './world.js?v=20261007b';
import {createRun,addShard,lightBeacon,canFinish,resolveDamage,restoreAtCheckpoint,wrapAngle} from './rules.js?v=20261007a';
const $=id=>document.getElementById(id),canvas=$('world');
const coarse=matchMedia('(pointer:coarse)').matches,reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
let atmosphere;
let low=coarse||innerWidth<720,renderer,world,hero,run=createRun(),mode='loading',previousMode='title',previousHelp='title',time=0,last=0,ready=false;
let player={x:0,z:31,y:0,vy:0,yaw:Math.PI,grounded:true,attack:0,attackCooldown:0,combo:0,comboWindow:0,dash:0,dashCooldown:0,invulnerable:0,gliding:false};
let cameraYaw=0,cameraPitch=.12,cameraDistance=8.3,camDrag=null,joystick={x:0,y:0,id:null},keys=new Set(),jumpHeld=false,toastUntil=0,interactIndex=-1,checkpoint={x:0,z:31},enemies=[],shards=[],effects=[],clockRate=1,hitStop=0,nearest=null;
let audio=null,audioEnabled=false,audioNext=0;
const camera=new T.PerspectiveCamera(53,innerWidth/innerHeight,.1,1800);
const heroMotion={step:{value:0},stride:{value:0}};
let target=new T.Vector3(),desired=new T.Vector3(),movement=new T.Vector2(),glider,sword,shadow,attackArc,mapCtx=$('map').getContext('2d'),qualityFrames=[];
const movementKeys=new Set(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','ShiftLeft','ShiftRight','KeyJ','KeyE']);
function message(text,duration=4){$('toast').textContent=text;$('toast').classList.add('visible');toastUntil=time+duration;}
function tone(f=440,d=.08,type='sine',gain=.05){if(!audioEnabled||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(0,audio.currentTime);g.gain.linearRampToValueAtTime(gain,audio.currentTime+.008);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d+.02);}
function soundToggle(){audioEnabled=!audioEnabled;if(audioEnabled){audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});tone(523,.3);}else audio?.suspend();$('sound').setAttribute('aria-pressed',String(audioEnabled));$('sound').setAttribute('aria-label',audioEnabled?'소리 끄기':'소리 켜기');$('sound').style.color=audioEnabled?'#ffe4a5':'';}
function setMode(next){mode=next;$('title-screen').hidden=next!=='title'&&next!=='loading';$('hud').hidden=!['playing','paused','help'].includes(next)||!ready||previousHelp==='title'&&next==='help';$('pause-screen').hidden=next!=='paused';$('help-screen').hidden=next!=='help';$('end-screen').hidden=next!=='won';keys.clear();jumpHeld=false;joystick.x=joystick.y=0;joystick.id=null;$('joystick').firstElementChild.style.transform='';camDrag=null;if(next==='playing')canvas.focus({preventScroll:true});else if(next==='paused')$('resume').focus();else if(next==='help')$('close-help').focus();else if(next==='won')$('again').focus();}
function startRun(){if(!ready)return;resetRun();setMode('playing');message(coarse?'왼쪽 조이스틱으로 이동 · 오른쪽 화면을 드래그해 둘러보세요.':'계곡의 빛을 찾아가 보세요. WASD 이동 · 화면 드래그로 둘러보기',6);}
function pause(){if(mode!=='playing')return;previousMode='playing';setMode('paused');}
function showHelp(){previousHelp=mode;setMode('help');}
$('start').addEventListener('click',startRun);$('pause').addEventListener('click',pause);$('resume').addEventListener('click',()=>setMode('playing'));$('help').addEventListener('click',showHelp);$('title-help').addEventListener('click',showHelp);$('close-help').addEventListener('click',()=>setMode(previousHelp==='paused'?'paused':'title'));$('restart').addEventListener('click',startRun);$('again').addEventListener('click',startRun);$('sound').addEventListener('click',soundToggle);$('interact').addEventListener('click',interact);
$('quality').value=low?'low':'high';$('quality').addEventListener('change',()=>{low=$('quality').value==='low';applyQuality();});
function applyQuality(){renderer.setPixelRatio(Math.min(devicePixelRatio||1,low?1:1.7));renderer.shadowMap.enabled=!low;world.grass.count=low?Math.min(13000,world.grass.userData.fullCount):world.grass.userData.fullCount;resize();}
function resetRun(){run=createRun();checkpoint={x:0,z:31};Object.assign(player,{x:0,z:31,y:heightAt(0,31),vy:0,yaw:Math.PI,grounded:true,attack:0,attackCooldown:0,combo:0,comboWindow:0,dash:0,dashCooldown:0,invulnerable:0,gliding:false});cameraYaw=0;cameraPitch=.12;cameraDistance=8.3;clockRate=1;hitStop=0;world.beacons.forEach(b=>b.lit=false);for(const e of enemies){e.hp=e.maxHp;e.dead=false;e.group.visible=true;e.x=e.homeX;e.z=e.homeZ;e.phase='idle';e.timer=0;e.hit=0;}for(const s of shards){s.taken=false;s.mesh.visible=true;}for(const e of effects){world.scene.remove(e.mesh);e.mesh.geometry.dispose();e.mesh.material.dispose();}effects=[];$('boss-health').hidden=true;camera.position.set(0,player.y+4.5,40);updateHUD();}
function jump(){if(mode!=='playing'||!player.grounded||run.stamina<6)return;player.vy=8.8;player.grounded=false;run.stamina-=6;tone(320,.08,'triangle');}
function dash(){if(mode!=='playing'||player.dashCooldown>0||run.stamina<26)return;player.dash=.22;player.dashCooldown=.65;player.invulnerable=.36;run.stamina-=26;tone(170,.1,'sawtooth',.025);spawnBurst(player.x,player.y+.6,player.z,0xb3f7db,8);}
function attack(){if(mode!=='playing'||player.attackCooldown>0||player.dash>0)return;player.combo=player.comboWindow>0?(player.combo%3)+1:1;player.comboWindow=.95;player.attack=.34;player.attackCooldown=player.combo===3?.58:.33;tone(player.combo===3?195:330,.1,'triangle',.06);let hits=0;for(const e of enemies){if(e.dead)continue;const dist=Math.hypot(player.x-e.x,player.z-e.z);const facing=wrapAngle(Math.atan2(e.x-player.x,e.z-player.z)-player.yaw);if(dist<e.radius+2.55&&Math.abs(facing)<1.6){e.hp-=player.combo===3?3:2;e.hit=.25;e.phase='stagger';e.timer=.45;e.x+=Math.sin(player.yaw)*.8;e.z+=Math.cos(player.yaw)*.8;hits++;spawnBurst(e.x,heightAt(e.x,e.z)+e.height*.55,e.z,0xffd59a,12);if(e.hp<=0){e.dead=true;e.group.visible=false;e.telegraph.visible=false;addShard(run);tone(730,.2,'sine');if(e.boss)message('수호자가 잠들었습니다. 이제 봉화에 다가가세요.');}}}if(hits&&!reduced)hitStop=.045;}
function takeHit(e){if(!resolveDamage(run,1,player.invulnerable>0))return;player.invulnerable=1.3;$('hit-overlay').style.opacity='1';setTimeout(()=>$('hit-overlay').style.opacity='0',200);tone(90,.17,'triangle');const angle=Math.atan2(player.x-e.x,player.z-e.z);player.x+=Math.sin(angle)*1.2;player.z+=Math.cos(angle)*1.2;spawnBurst(player.x,player.y+.8,player.z,0xffb293,8);if(run.hp===0){restoreAtCheckpoint(run);player.x=checkpoint.x;player.z=checkpoint.z;player.y=heightAt(player.x,player.z);player.vy=0;player.invulnerable=3;message('빛이 다시 모였습니다. 가장 최근 봉화에서 이어가요.',5);}}
function interact(){if(mode!=='playing')return;if(canFinish(run)&&Math.hypot(player.x-GATE.x,player.z-(GATE.z+9))<5){run.finished=true;setMode('won');$('end-stats').innerHTML=`<span>되살린 봉화<br><strong>3 / 3</strong></span><span>빛의 조각<br><strong>${run.shards}개</strong></span><span>탐험 시간<br><strong>${Math.floor(run.time/60)}분 ${Math.floor(run.time%60)}초</strong></span>`;tone(523,1);return;}if(interactIndex<0||Math.hypot(player.x-BEACONS[interactIndex].x,player.z-BEACONS[interactIndex].z)>4.5)return;const i=interactIndex,guards=enemies.filter(e=>e.beacon===i&&!e.dead).length;if(guards){message('먼저 봉화 주변의 수호자를 물리쳐 주세요.');return;}if(lightBeacon(run,i,guards)){world.beacons[i].lit=true;checkpoint={x:BEACONS[i].x,z:BEACONS[i].z+4};spawnBurst(BEACONS[i].x,heightAt(BEACONS[i].x,BEACONS[i].z)+3,BEACONS[i].z,0xafffd2,32);[523,659,784].forEach((f,j)=>setTimeout(()=>tone(f,.65),j*140));message(canFinish(run)?'세 봉화가 깨어났습니다. 북쪽 성채의 빛으로 돌아가세요.':`${BEACONS[i].name}가 깨어났습니다. 체력이 회복됐어요.`,5);}}
addEventListener('keydown',e=>{if(e.code==='Tab'&&['paused','help','won'].includes(mode)){const dialog=$(mode==='paused'?'pause-screen':mode==='help'?'help-screen':'end-screen');const controls=[...dialog.querySelectorAll('button:not([disabled]),a,select')];const i=controls.indexOf(document.activeElement);if((e.shiftKey&&i<=0)||(!e.shiftKey&&i===controls.length-1)){e.preventDefault();controls[e.shiftKey?controls.length-1:0].focus();}return;}if(e.metaKey||e.ctrlKey||e.altKey||e.target instanceof HTMLSelectElement)return;if(e.code==='Escape'){e.preventDefault();if(mode==='playing')pause();else if(mode==='paused')setMode('playing');else if(mode==='help')setMode(previousHelp==='paused'?'paused':'title');return;}if(mode!=='playing')return;if(movementKeys.has(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code==='Space'){jumpHeld=true;jump();}if(e.code==='KeyJ')attack();if(e.code==='ShiftLeft'||e.code==='ShiftRight')dash();if(e.code==='KeyE')interact();});
addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='Space')jumpHeld=false;});addEventListener('blur',()=>{if(mode==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='playing')pause();});
canvas.addEventListener('pointerdown',e=>{if(mode!=='playing')return;camDrag={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!camDrag||e.pointerId!==camDrag.id)return;cameraYaw-=(e.clientX-camDrag.x)*.005;cameraPitch=T.MathUtils.clamp(cameraPitch+(e.clientY-camDrag.y)*.003,-.06,.8);camDrag.x=e.clientX;camDrag.y=e.clientY;});for(const n of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(n,()=>camDrag=null);canvas.addEventListener('wheel',e=>{if(mode==='playing'){e.preventDefault();cameraDistance=T.MathUtils.clamp(cameraDistance+e.deltaY*.006,4.6,12);}}, {passive:false});
const stick=$('joystick');stick.addEventListener('pointerdown',e=>{e.preventDefault();if(mode!=='playing')return;joystick.id=e.pointerId;stick.setPointerCapture(e.pointerId);moveStick(e);});stick.addEventListener('pointermove',e=>{if(joystick.id===e.pointerId)moveStick(e);});function moveStick(e){const b=stick.getBoundingClientRect(),radius=b.width*.32,x=e.clientX-b.left-b.width/2,y=e.clientY-b.top-b.height/2,l=Math.max(radius,Math.hypot(x,y));joystick.x=x/l;joystick.y=y/l;stick.firstElementChild.style.transform=`translate(${joystick.x*radius}px,${joystick.y*radius}px)`;}for(const n of ['pointerup','pointercancel','lostpointercapture'])stick.addEventListener(n,()=>{joystick.x=joystick.y=0;joystick.id=null;stick.firstElementChild.style.transform='';});
document.querySelectorAll('[data-action]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(b.dataset.action==='jump'){jumpHeld=true;jump();}else if(b.dataset.action==='attack')attack();else dash();});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>{if(b.dataset.action==='jump')jumpHeld=false;});});
function spawnBurst(x,y,z,c,n=12){for(let i=0;i<n;i++){const mesh=new T.Mesh(new T.OctahedronGeometry(.04+Math.random()*.08,0),new T.MeshBasicMaterial({color:c,transparent:true,opacity:1}));mesh.position.set(x,y,z);world.scene.add(mesh);effects.push({mesh,v:new T.Vector3((Math.random()-.5)*6,Math.random()*5+1,(Math.random()-.5)*6),life:.55+Math.random()*.35,total:.9});}}
function makeEnemy(x,z,beacon,boss=false){const height=boss?3.8:1.65,group=world.instantiate('cavity-monster',height);group.position.set(x,heightAt(x,z),z);group.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.userData.normalEmissive=o.material.emissive.clone();}});world.scene.add(group);const radius=boss?1.5:.65;const telegraph=new T.Mesh(new T.RingGeometry(.2,boss?4.5:2.6,64),new T.MeshBasicMaterial({color:0xfb7764,transparent:true,opacity:.4,side:T.DoubleSide,depthWrite:false}));telegraph.rotation.x=-Math.PI/2;telegraph.visible=false;world.scene.add(telegraph);const hp=boss?22:6;return{group,telegraph,x,z,homeX:x,homeZ:z,beacon,boss,height,radius,hp,maxHp:hp,phase:'idle',timer:0,hit:0,dead:false,angle:0};}
function setupActors(){hero=world.instantiate('tooth-hero',1.8);hero.traverse(o=>{if(!o.isMesh)return;o.material=o.material.clone();o.material.onBeforeCompile=s=>{s.uniforms.heroStep=heroMotion.step;s.uniforms.heroStride=heroMotion.stride;s.vertexShader=s.vertexShader.replace('#include <common>','#include <common>\nuniform float heroStep;uniform float heroStride;').replace('#include <begin_vertex>','#include <begin_vertex>\nfloat foot=1.-smoothstep(-.85,-.32,position.y);float side=position.x>0.?1.:-1.;transformed.z+=sin(heroStep+side*1.5708)*foot*heroStride*.18;transformed.y+=max(0.,cos(heroStep+side*1.5708))*foot*heroStride*.06;');};});world.scene.add(hero);
 // A crafted luminous blade, visible through all three combo arcs.
 sword=new T.Group();const blade=new T.Mesh(new T.ConeGeometry(.12,1.6,4),new T.MeshStandardMaterial({color:0xbdfbdd,emissive:0x5ecfae,emissiveIntensity:.7,metalness:.4,roughness:.25}));blade.position.y=.8;sword.add(blade);const guard=new T.Mesh(new T.BoxGeometry(.5,.08,.14),new T.MeshStandardMaterial({color:0xc8a66c,metalness:.65,roughness:.4}));sword.add(guard);world.scene.add(sword);
 attackArc=new T.Mesh(new T.RingGeometry(1.8,2.5,40,1,0,Math.PI*1.15),new T.MeshBasicMaterial({color:0xd4ffe1,side:T.DoubleSide,transparent:true,opacity:.7,depthWrite:false}));attackArc.rotation.x=-Math.PI/2;world.scene.add(attackArc);
 glider=new T.Group();const shape=new T.Shape();shape.moveTo(-2.3,0);shape.quadraticCurveTo(0,2.2,2.3,0);shape.quadraticCurveTo(0,.65,-2.3,0);const wing=new T.Mesh(new T.ShapeGeometry(shape,24),new T.MeshStandardMaterial({color:0xe1c88f,roughness:.95,side:T.DoubleSide}));wing.rotation.x=-Math.PI/2;glider.add(wing);for(const side of [-1,1]){const rope=new T.Mesh(new T.CylinderGeometry(.015,.015,1.65,5),new T.MeshBasicMaterial({color:0xb6a675}));rope.rotation.z=side*.65;rope.position.set(side*.55,-.55,0);glider.add(rope);}world.scene.add(glider);
 const shadowCanvas=document.createElement('canvas');shadowCanvas.width=shadowCanvas.height=64;const sx=shadowCanvas.getContext('2d'),gradient=sx.createRadialGradient(32,32,1,32,32,32);gradient.addColorStop(0,'rgba(15,35,19,.55)');gradient.addColorStop(1,'rgba(15,35,19,0)');sx.fillStyle=gradient;sx.fillRect(0,0,64,64);shadow=new T.Mesh(new T.PlaneGeometry(2.5,2.5),new T.MeshBasicMaterial({map:new T.CanvasTexture(shadowCanvas),transparent:true,depthWrite:false}));shadow.rotation.x=-Math.PI/2;world.scene.add(shadow);
 for(let i=0;i<3;i++){const b=BEACONS[i];enemies.push(makeEnemy(b.x-3,b.z+4,i,i===2),makeEnemy(b.x+3,b.z+2,i));if(i===1)enemies.push(makeEnemy(b.x+1,b.z-4,i));}
 const positions=[[0,26],[1,21],[-3,16],[-8,12],[-13,10],[-17,11],[6,18],[12,10],[17,4],[21,0],[14,-10],[8,-19],[-2,-24],[-9,-24],[-15,-19],[-20,-14],[0,-28],[11,12],[11,11],[11,8]];
 const geo=new T.OctahedronGeometry(.25,1),mat=new T.MeshStandardMaterial({color:0xffdf94,emissive:0xe9ba58,emissiveIntensity:.7,metalness:.5,roughness:.25});positions.forEach(([x,z],i)=>{const mesh=new T.Mesh(geo,mat);mesh.position.set(x,heightAt(x,z)+(i===18?5:i===19?7:.8),z);mesh.castShadow=true;world.scene.add(mesh);shards.push({mesh,x,z,y:mesh.position.y,taken:false});});
}
function updatePlayer(dt){
 run.time+=dt;for(const key of ['attack','attackCooldown','comboWindow','dash','dashCooldown','invulnerable'])player[key]=Math.max(0,player[key]-dt);
 const mx=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+joystick.x,mz=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+joystick.y;movement.set(mx,mz);if(movement.length()>1)movement.normalize();const moving=movement.length()>.1;
 const dx=movement.x*Math.cos(cameraYaw)+movement.y*Math.sin(cameraYaw),dz=movement.y*Math.cos(cameraYaw)-movement.x*Math.sin(cameraYaw);if(moving&&player.attack<=0){const targetYaw=Math.atan2(dx,dz);player.yaw+=wrapAngle(targetYaw-player.yaw)*Math.min(1,dt*14);}
 const pond=Math.hypot(player.x+32,player.z-5)<8;let speed=(player.attack>0?2.1:5.5)*(pond?.7:1);if(player.dash>0){player.x+=Math.sin(player.yaw)*17*dt;player.z+=Math.cos(player.yaw)*17*dt;}else{player.x+=dx*speed*dt;player.z+=dz*speed*dt;}
 player.x=T.MathUtils.clamp(player.x,-45,45);player.z=T.MathUtils.clamp(player.z,-42,43);
 for(const r of world.rigid){const d=Math.hypot(player.x-r.x,player.z-r.z),min=r.r+.38;if(d<min&&d>.001){player.x=r.x+(player.x-r.x)*min/d;player.z=r.z+(player.z-r.z)*min/d;}}
 const ground=heightAt(player.x,player.z);player.gliding=!player.grounded&&player.vy<1&&jumpHeld&&run.stamina>0;const updraft=Math.hypot(player.x-11,player.z-12)<2.3&&!player.grounded;
 if(updraft&&player.y<ground+10){player.vy=Math.max(player.vy,5);player.gliding=jumpHeld;}else if(!player.grounded){player.vy-=dt*(player.gliding?5:23);if(player.gliding)player.vy=Math.max(player.vy,-1.7);}
 player.y+=player.vy*dt;if(player.y<=ground){player.y=ground;player.vy=0;player.grounded=true;}else if(player.y>ground+.2){player.grounded=false;}
 run.stamina=T.MathUtils.clamp(run.stamina+dt*(player.gliding?-15:player.dash>0?0:player.grounded?24:8),0,100);
 heroMotion.step.value=time*13;heroMotion.stride.value=moving&&player.grounded?1:0;
 hero.position.set(player.x,player.y+(moving&&player.grounded?Math.abs(Math.sin(time*13))*.10:Math.sin(time*2)*.018),player.z);hero.rotation.set(player.gliding?.10:0,player.yaw,moving&&player.grounded?Math.sin(time*13)*.045:0);hero.visible=player.invulnerable<.1||Math.floor(time*13)%2===0;
 glider.visible=player.gliding;glider.position.set(player.x,player.y+2.3,player.z);glider.rotation.set(0,player.yaw,Math.sin(time*2)*.04);
 shadow.position.set(player.x,ground+.035,player.z);shadow.material.opacity=Math.max(.12,1-(player.y-ground)*.07);
 const q=player.attack>0?1-player.attack/.34:0;sword.position.set(player.x+Math.sin(player.yaw+1)*.65,player.y+.75,player.z+Math.cos(player.yaw+1)*.65);sword.rotation.set(player.attack>0?1.1:0,player.yaw,player.attack>0?-1.4+q*4:-.3);attackArc.visible=player.attack>.05;attackArc.position.set(player.x,player.y+.7,player.z);attackArc.rotation.set(-Math.PI/2,0,-player.yaw-q*3);attackArc.material.opacity=(1-q)*.65;
 for(const s of shards){if(s.taken)continue;s.mesh.position.y=s.y+Math.sin(time*2+s.x)*.15;s.mesh.rotation.y=time;if(Math.hypot(player.x-s.x,player.z-s.z)<1.15&&Math.abs(player.y+.7-s.mesh.position.y)<1.3){s.taken=true;s.mesh.visible=false;addShard(run);tone(850,.14,'sine',.025);spawnBurst(s.x,s.y,s.z,0xffdda0,5);}}
}
function updateEnemies(dt){nearest=null;let nearestDist=100;
 for(const e of enemies){if(e.dead)continue;const d=Math.hypot(player.x-e.x,player.z-e.z);if(d<nearestDist){nearest=e;nearestDist=d;}e.hit=Math.max(0,e.hit-dt);e.timer-=dt;e.angle=Math.atan2(player.x-e.x,player.z-e.z);
 if(e.phase==='stagger'&&e.timer<=0)e.phase='chase';
 else if(e.phase==='windup'&&e.timer<=0){e.phase='strike';e.timer=.30;if(d<(e.boss?4.6:2.7)&&player.y-heightAt(player.x,player.z)<2.3)takeHit(e);spawnBurst(e.x,heightAt(e.x,e.z)+.2,e.z,0xf2b178,e.boss?20:8);}
 else if(e.phase==='strike'&&e.timer<=0){e.phase='rest';e.timer=e.boss?1.6:1.1;}
 else if(e.phase==='rest'&&e.timer<=0)e.phase='chase';
 else if(e.phase==='idle'&&d<12)e.phase='chase';
 else if(e.phase==='chase'){if(d>20){e.phase='idle';}else if(d<(e.boss?3.9:2.0)){e.phase='windup';e.timer=e.boss?1.25:.8;tone(e.boss?140:190,.09,'triangle',.02);}else{const speed=e.boss?1.35:1.65;e.x+=Math.sin(e.angle)*speed*dt;e.z+=Math.cos(e.angle)*speed*dt;}}
 const y=heightAt(e.x,e.z);e.group.position.set(e.x,y+(e.phase==='chase'?Math.abs(Math.sin(time*7+e.homeX))*.10:0),e.z);e.group.rotation.y=e.angle;e.group.rotation.z=e.phase==='windup'?Math.sin(time*30)*.025:e.phase==='chase'?Math.sin(time*7)*.055:0;e.group.traverse(o=>{if(o.isMesh){o.material.emissive.copy(e.hit>0?new T.Color(0xc28248):o.userData.normalEmissive);o.material.emissiveIntensity=e.hit>0?1:.05;}});
 e.telegraph.visible=e.phase==='windup'||e.phase==='strike';e.telegraph.position.set(e.x,y+.055,e.z);e.telegraph.material.opacity=e.phase==='strike'?.6:.16+(1-e.timer/(e.boss?1.25:.8))*.38;
 }
 const foe=enemies.find(e=>e.boss&&!e.dead&&Math.hypot(e.x-player.x,e.z-player.z)<15)||(nearestDist<7?nearest:null);$('boss-health').hidden=!foe;if(foe){$('boss-health').querySelector('span').textContent=foe.boss?'유적의 수호자':'암석 수호자';$('boss-health').querySelector('i').style.width=`${Math.max(0,foe.hp/foe.maxHp*100)}%`;}
}
let hudTimer=0;
function updateHUD(){
 $('hearts').textContent='♥ '.repeat(run.hp)+'♡ '.repeat(5-run.hp);$('hearts').setAttribute('aria-label',`체력 ${run.hp} / 5`);$('stamina').style.width=run.stamina+'%';$('shards').textContent=run.shards;$('quest-count').textContent=`${run.lit.filter(Boolean).length} / 3 봉화`;$('quest-title').textContent=canFinish(run)?'북쪽 성채의 빛으로 돌아가세요':'세 봉화에 빛을 돌려주세요';$('combo').textContent=player.comboWindow>0?`${player.combo}연속 공격`:'';
 interactIndex=-1;let distance=Infinity;for(let i=0;i<3;i++){if(run.lit[i])continue;const b=BEACONS[i],d=Math.hypot(player.x-b.x,player.z-b.z);if(d<distance){distance=d;interactIndex=i;}}
 const canGate=canFinish(run)&&Math.hypot(player.x-GATE.x,player.z-(GATE.z+9))<5;const near=distance<4.5;$('interact').hidden=!near&&!canGate;if(near||canGate){const guards=enemies.filter(e=>e.beacon===interactIndex&&!e.dead).length;$('interact').innerHTML=canGate?'성채에 빛 전달하기 <kbd>E</kbd>':guards?`수호자 ${guards}마리 남음 <kbd>E</kbd>`:'봉화 깨우기 <kbd>E</kbd>';}
 const b=canFinish(run)?{x:GATE.x,z:GATE.z+9}:BEACONS[interactIndex];if(b){const relative=wrapAngle(Math.atan2(b.x-player.x,b.z-player.z)-cameraYaw-Math.PI);$('objective-arrow').style.transform=`translateX(-50%) rotate(${-relative}rad)`;$('objective-arrow').style.left=(50+T.MathUtils.clamp(relative,-1.7,1.7)*20)+'%';}
 const c=mapCtx;c.clearRect(0,0,160,160);c.save();c.translate(80,80);c.fillStyle='#264634';c.beginPath();c.arc(0,0,79,0,Math.PI*2);c.fill();c.strokeStyle='#a5b57f24';c.lineWidth=1;for(let i=-60;i<=60;i+=20){c.beginPath();c.moveTo(i,-80);c.lineTo(i,80);c.moveTo(-80,i);c.lineTo(80,i);c.stroke();}const scale=1.55;for(let i=0;i<3;i++){const b=BEACONS[i];c.fillStyle=run.lit[i]?'#97efbd':'#f2d497';c.beginPath();c.arc(b.x*scale,b.z*scale,run.lit[i]?3:4,0,Math.PI*2);c.fill();}c.strokeStyle='#e8d19d';c.strokeRect(GATE.x*scale-3,GATE.z*scale-3,6,6);for(const e of enemies){if(e.dead||Math.hypot(e.x-player.x,e.z-player.z)>16)continue;c.fillStyle='#ec967c';c.beginPath();c.arc(e.x*scale,e.z*scale,2,0,Math.PI*2);c.fill();}c.translate(player.x*scale,player.z*scale);c.rotate(-player.yaw);c.fillStyle='#fff4cd';c.beginPath();c.moveTo(0,6);c.lineTo(-4,-4);c.lineTo(4,-4);c.closePath();c.fill();c.restore();
}
function updateCamera(dt){if(mode==='title'||mode==='loading'){const a=reduced?0:time*.018;camera.position.set(9+Math.sin(a)*3,6,39);camera.lookAt(-3,4,-12);return;}
 target.set(player.x,player.y+1.3,player.z);desired.set(player.x+Math.sin(cameraYaw)*cameraDistance,player.y+2.3+Math.sin(cameraPitch)*cameraDistance,player.z+Math.cos(cameraYaw)*cameraDistance);desired.y=Math.max(desired.y,heightAt(desired.x,desired.z)+1.5);camera.position.lerp(desired,1-Math.exp(-dt*7));camera.lookAt(target);}
function renderFrame(){renderer.info.reset();if(atmosphere&&!low)atmosphere.render(world.scene,camera);else renderer.render(world.scene,camera);}
function resize(){if(!renderer)return;renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();atmosphere?.resize();}addEventListener('resize',resize);
function tick(ms){requestAnimationFrame(tick);const raw=Math.min((ms-last)/1000||.016,.05);last=ms;time+=raw;if(!ready){if(world){world.update(time);updateCamera(raw);renderFrame();}return;}const dt=hitStop>0?0:raw;hitStop=Math.max(0,hitStop-raw);
 if(mode==='playing'){updatePlayer(dt);updateEnemies(dt);hudTimer-=raw;if(hudTimer<=0){updateHUD();hudTimer=.12;}if(toastUntil<time)$('toast').classList.remove('visible');if(audioEnabled&&time>audioNext){const notes=[196,246.94,293.66,392,440];tone(notes[Math.floor(time/5)%notes.length],1.5,'sine',.007);audioNext=time+2.2;}}
 if(mode!=='paused'&&mode!=='help'){world.update(time);for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.life-=raw;e.v.y-=raw*8;e.mesh.position.addScaledVector(e.v,raw);e.mesh.material.opacity=Math.max(0,e.life/e.total);if(e.life<=0){world.scene.remove(e.mesh);e.mesh.geometry.dispose();e.mesh.material.dispose();effects.splice(i,1);}}}
 updateCamera(raw);renderFrame();
 // Expose a read-only snapshot for diagnostics; no mutation or win shortcuts.
 window.BD_ENAMEL_STATE={version:'2026.10.07-first-region',mode,hp:run.hp,stamina:Math.round(run.stamina),lit:[...run.lit],shards:run.shards,position:{x:player.x,y:player.y,z:player.z},grounded:player.grounded,gliding:player.gliding,enemies:enemies.map(e=>({x:e.x,z:e.z,hp:e.hp,dead:e.dead,phase:e.phase,beacon:e.beacon})),drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,models:Object.keys(world.assets),quality:low?'low':'high'};
}
async function init(){try{renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,low?1:1.7));renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.shadowMap.enabled=!low;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.info.autoReset=false;atmosphere=new Atmosphere(renderer);atmosphere.resize();
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();pause();$('pause-title').textContent='그래픽 연결이 잠시 끊겼어요';$('resume').disabled=true;$('restart').textContent='페이지를 새로 열어 다시 시작';$('restart').onclick=()=>location.reload();});canvas.addEventListener('webglcontextrestored',()=>location.reload());
 world=await buildWorld(renderer,(progress,text)=>{$('load-bar').style.width=progress*100+'%';$('load-detail').textContent=text;},low);world.grass.userData.fullCount=world.grass.count;setupActors();ready=true;resetRun();setMode('title');$('load-bar').style.width='100%';$('load-label').textContent='계곡으로 들어가기';$('load-detail').textContent='세계 준비 완료 · 설치 없이 플레이';$('start').disabled=false;requestAnimationFrame(tick);
 }catch(error){console.error('Enamel initialization failed',error);$('load-label').textContent='다시 불러오기';$('start').disabled=false;$('start').addEventListener('click',()=>location.reload(),{once:true});$('load-detail').textContent='3D 화면을 준비하지 못했습니다. 최신 브라우저에서 다시 시도해 주세요.';}}
init();
