import * as T from '../arcade/vendor/three.module.min.js';
import {mergeVertices} from '../arcade/vendor/utils/BufferGeometryUtils.js';
import {GLTFLoader} from '../arcade/vendor/loaders/GLTFLoader.js';
export const BEACONS=[{x:-21,z:8,name:'바람의 봉화'},{x:21,z:-5,name:'숲의 봉화'},{x:-17,z:-23,name:'여명의 봉화'}];
export const GATE={x:0,z:-34};
export function heightAt(x,z){const broad=Math.sin(x*.057)*Math.cos(z*.049)*2.7+Math.sin(z*.105+x*.045)*1.2;const basin=1.5*Math.exp(-((x+30)**2+(z-4)**2)/210);return broad-basin+Math.max(0,Math.abs(x)-39)*.28+Math.max(0,Math.abs(z)-42)*.22;}
let seed=41007;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
const color=c=>new T.Color(c),V=(x,y,z)=>new T.Vector3(x,y,z);
const standard=(c,rough=1,metal=0)=>new T.MeshStandardMaterial({color:c,roughness:rough,metalness:metal});
export async function buildWorld(renderer,onProgress,low){
 const scene=new T.Scene();scene.fog=new T.FogExp2(0xb5d4c6,.0038);
 const sunPosition=V(-65,80,-65),sunDir=sunPosition.clone().normalize();
 const skyMaterial=new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{sun:{value:sunDir}},vertexShader:'varying vec3 vP;void main(){vP=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`varying vec3 vP;uniform vec3 sun;void main(){vec3 d=normalize(vP);float y=max(d.y,0.);vec3 c=mix(vec3(.68,.81,.76),vec3(.10,.40,.60),pow(y,.45));float s=max(dot(d,sun),0.);c+=vec3(1.,.72,.31)*pow(s,180.)*1.3+c*.16*pow(s,8.);gl_FragColor=vec4(c,1.);#include <tonemapping_fragment>\n#include <colorspace_fragment>}`.replace(';#include',';\n#include')});
 const sky=new T.Mesh(new T.SphereGeometry(650,32,20),skyMaterial);scene.add(sky);
 const envScene=new T.Scene();envScene.add(new T.Mesh(new T.SphereGeometry(10,24,16),skyMaterial));const pmrem=new T.PMREMGenerator(renderer);const env=pmrem.fromScene(envScene,.05,.1,100);scene.environment=env.texture;scene.environmentIntensity=.65;pmrem.dispose();
 scene.add(new T.HemisphereLight(0xdff5e9,0x465b30,1.4));const sun=new T.DirectionalLight(0xffe5b0,2.6);sun.position.copy(sunPosition);sun.castShadow=true;sun.shadow.mapSize.set(low?1024:2048,low?1024:2048);Object.assign(sun.shadow.camera,{left:-47,right:47,top:47,bottom:-47,near:1,far:220});sun.shadow.normalBias=.05;sun.shadow.bias=-.00015;scene.add(sun,sun.target);
 const clock={value:0};
 const textureLoader=new T.TextureLoader();const textureTasks=[];
 function surface(material,name,repeat=1,normal=.5){
  for(const [suffix,slot]of [['color','map'],['normal','normalMap']]){const promise=textureLoader.loadAsync('/assets/enamel-materials/'+name+'-'+suffix+'.jpg').then(t=>{t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(repeat,repeat);t.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());if(slot==='map')t.colorSpace=T.SRGBColorSpace;material[slot]=t;material.needsUpdate=true;});textureTasks.push(promise);}
  material.normalScale=new T.Vector2(normal,normal);
 }

 const geometry=new T.PlaneGeometry(150,150,190,190);geometry.rotateX(-Math.PI/2);const a=geometry.attributes.position,colors=[];
 for(let i=0;i<a.count;i++){const x=a.getX(i),z=a.getZ(i);a.setY(i,heightAt(x,z));const n=(Math.sin(x*.32+z*.18)+Math.sin(x*.77-z*.51))*.5;const c=color('#547842').lerp(color('#9dab5e'),(n+1)*.33);const path=Math.abs(x-5*Math.sin(z*.12))<2.4&&z>-34&&z<39;if(path)c.lerp(color('#b5a783'),.75);colors.push(c.r,c.g,c.b);}geometry.setAttribute('color',new T.Float32BufferAttribute(colors,3));geometry.computeVertexNormals();
 const groundMat=standard(0xffffff);groundMat.vertexColors=true;surface(groundMat,'grass_ground',46,.25);groundMat.onBeforeCompile=s=>{s.vertexShader=s.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 terrainPosition;').replace('#include <begin_vertex>','#include <begin_vertex>\nterrainPosition=position;');s.fragmentShader=s.fragmentShader.replace('#include <common>','#include <common>\nvarying vec3 terrainPosition;').replace('#include <color_fragment>','#include <color_fragment>\ndiffuseColor.rgb=mix(diffuseColor.rgb,vColor,0.45);float grain=sin(terrainPosition.x*.93+sin(terrainPosition.z*1.77))*sin(terrainPosition.z*.48+sin(terrainPosition.x*.68))*.016;diffuseColor.rgb+=grain;');};const ground=new T.Mesh(geometry,groundMat);ground.receiveShadow=true;scene.add(ground);
 const stone=standard('#9b9d83'),stoneDark=standard('#606f60'),gold=standard('#d9b879',.38,.6),ivory=standard('#dfdec1',.65),glow=new T.MeshStandardMaterial({color:0x9ff5d1,emissive:0x64e7b9,emissiveIntensity:2,roughness:.4});
 surface(stone,'mossy_rock',1.4,.65);surface(stoneDark,'mossy_rock',1,.55);surface(ivory,'mossy_sandstone',1,.40);
 const rigid=[];
 function object(g,m,x,y,z,scale=1,shadow=true){const o=new T.Mesh(g,m);o.position.set(x,y,z);o.scale.setScalar(scale);o.castShadow=shadow;o.receiveShadow=shadow;scene.add(o);return o;}
 let rockGeo=mergeVertices(new T.IcosahedronGeometry(1,3));const rp=rockGeo.attributes.position;for(let i=0;i<rp.count;i++){const k=1+.14*Math.sin(rp.getX(i)*15+rp.getZ(i)*13)*Math.cos(rp.getY(i)*10);rp.setXYZ(i,rp.getX(i)*k,rp.getY(i)*k*.7,rp.getZ(i)*k);}rockGeo.computeVertexNormals();
 for(let i=0;i<100;i++){let x=(rand()-.5)*110,z=(rand()-.5)*110;if(Math.hypot(x,z-28)<12)continue;const scale=.6+rand()*2.6;const r=object(rockGeo,i%3?stone:stoneDark,x,heightAt(x,z)-scale*.18,z,scale);r.rotation.set(rand(),rand()*6,rand()*.5);if(scale>1.5)rigid.push({x,z,r:scale*.65});}
 // Distant sculpted mountain ridges give a continuous horizon, never a flat background image.
 for(let ring=0;ring<2;ring++){
  const ridgeGeo=new T.PlaneGeometry(580,580,180,180);ridgeGeo.rotateX(-Math.PI/2);const rpos=ridgeGeo.attributes.position;const cs=[];
  for(let i=0;i<rpos.count;i++){const x=rpos.getX(i),z=rpos.getZ(i),r=Math.hypot(x,z),theta=Math.atan2(x,z);const envelope=Math.exp(-((r-(ring?220:132))**2)/(ring?1400:900));const peaks=25+23*Math.sin(theta*5+ring)**2+17*Math.sin(theta*11+1)**2;const detail=Math.sin(x*.10+Math.sin(z*.11))*4+Math.sin(x*.27-z*.13)*2;rpos.setY(i,-6+envelope*(peaks+detail));const c=color(ring?'#819e91':'#768d78').lerp(color('#bfc9ae'),Math.max(0,(peaks-45)/40));cs.push(c.r,c.g,c.b);}
  ridgeGeo.setAttribute('color',new T.Float32BufferAttribute(cs,3));ridgeGeo.computeVertexNormals();const m=standard(0xffffff);m.vertexColors=true;object(ridgeGeo,m,0,0,0,1,false);
 }
 // Tree placement is independent of the model, allowing reviewed authored assets.
 const trees=[];
 for(let i=0;i<80;i++){const x=(rand()-.5)*116,z=(rand()-.5)*116;if(Math.abs(x)<10||BEACONS.some(b=>Math.hypot(x-b.x,z-b.z)<7)||Math.hypot(x,z-28)<12)continue;const tree=new T.Object3D();tree.position.set(x,heightAt(x,z),z);trees.push(tree);rigid.push({x,z,r:.45});}
 // Instanced grass. Every blade bends in the same wind field; vertex gradient keeps the roots shaded.
 const blade=new T.PlaneGeometry(.085,.36,1,4);blade.translate(0,.18,0);const bp=blade.attributes.position;for(let i=0;i<bp.count;i++){const h=bp.getY(i)/.36;bp.setX(i,bp.getX(i)*Math.pow(Math.max(0,1-h),.6)+h*h*.09);bp.setZ(i,h*h*.035);}
 const grassMat=new T.MeshLambertMaterial({color:0xffffff,side:T.DoubleSide,vertexColors:false});grassMat.onBeforeCompile=s=>{s.uniforms.windTime=clock;s.vertexShader=s.vertexShader.replace('#include <common>','#include <common>\nuniform float windTime; varying float bladeHeight;').replace('#include <begin_vertex>',`#include <begin_vertex>\nbladeHeight=position.y; vec3 root=(instanceMatrix*vec4(0.,0.,0.,1.)).xyz;float gust=sin(root.x*.13+root.z*.12+windTime*1.1)+sin(root.x*.4-windTime*1.8)*.3;transformed.x+=gust*pow(position.y,2.)*.23;`);s.vertexShader=s.vertexShader.replace('#include <beginnormal_vertex>','vec3 objectNormal=vec3(0.,1.,0.);');s.fragmentShader=s.fragmentShader.replace('#include <normal_fragment_begin>','#include <normal_fragment_begin>\nnormal=normalize(vViewPosition*0.+vec3(0.,1.,.2));').replace('#include <common>','#include <common>\nvarying float bladeHeight;').replace('#include <color_fragment>','#include <color_fragment>\ndiffuseColor.rgb*=mix(vec3(.48,.57,.37),vec3(1.1,1.13,.88),clamp(bladeHeight,0.,1.));');};
 const grass=new T.InstancedMesh(blade,grassMat,low?14000:45000),dummy=new T.Object3D();let count=0;for(let i=0;i<grass.count;i++){const x=(rand()-.5)*102,z=(rand()-.5)*102;if((Math.abs(x-5*Math.sin(z*.12))<2.5&&z>-35&&z<41)||Math.hypot(x+32,z-5)<10||BEACONS.some(b=>Math.hypot(x-b.x,z-b.z)<3.1))continue;dummy.position.set(x,heightAt(x,z)-.03,z);dummy.rotation.set(0,rand()*Math.PI,0);const size=.65+rand()*.95;dummy.scale.set(size,size,size);dummy.updateMatrix();grass.setMatrixAt(count,dummy.matrix);grass.setColorAt(count,color('#659a46').lerp(color('#9eb64b'),rand()*.5));count++;}grass.count=count;grass.instanceMatrix.needsUpdate=true;grass.receiveShadow=true;scene.add(grass);
 // Low wildflower clusters are rooted in the terrain, with stems and cupped petals.
 const flowerCount=260,stems=new T.InstancedMesh(new T.CylinderGeometry(.012,.016,.24,4),standard('#51714a'),flowerCount),petals=new T.InstancedMesh(new T.SphereGeometry(.048,6,4),standard('#f8e8b3'),flowerCount*5),centers=new T.InstancedMesh(new T.SphereGeometry(.025,6,4),standard('#edba59'),flowerCount);
 for(let i=0;i<flowerCount;i++){const x=(rand()-.5)*78,z=(rand()-.5)*80,groundY=heightAt(x,z),h=.7+rand()*.6;dummy.position.set(x,groundY+.12*h,z);dummy.scale.set(1,h,1);dummy.rotation.set(0,0,0);dummy.updateMatrix();stems.setMatrixAt(i,dummy.matrix);dummy.position.y=groundY+.24*h;dummy.scale.set(1,1,1);dummy.updateMatrix();centers.setMatrixAt(i,dummy.matrix);const tint=color(i%3?'#f8e8b3':'#c7b9e0');for(let j=0;j<5;j++){const a=j/5*Math.PI*2;dummy.position.set(x+Math.sin(a)*.043,groundY+.24*h-.009,z+Math.cos(a)*.043);dummy.scale.set(.7,.28,1);dummy.rotation.set(0,a,0);dummy.updateMatrix();petals.setMatrixAt(i*5+j,dummy.matrix);petals.setColorAt(i*5+j,tint);}}
 stems.receiveShadow=petals.receiveShadow=centers.receiveShadow=true;scene.add(stems,petals,centers);
 // Shimmering spring with moving normals, shoreline foam and sun glints.
 const waterMaterial=new T.ShaderMaterial({transparent:true,uniforms:{time:clock,sun:{value:sunDir}},vertexShader:`varying vec3 w;varying vec3 local;void main(){local=position;w=(modelMatrix*vec4(position,1.)).xyz;gl_Position=projectionMatrix*viewMatrix*vec4(w,1.);}`,fragmentShader:`uniform float time;uniform vec3 sun;varying vec3 w;varying vec3 local;void main(){float t=time*.5;vec3 n=normalize(vec3(sin(w.x*2.+w.z+t)*.08,1.,cos(w.z*2.4-w.x*.7-t)*.08));vec3 v=normalize(cameraPosition-w);float f=pow(1.-max(dot(n,v),0.),3.);vec3 c=mix(vec3(.10,.43,.39),vec3(.60,.79,.75),f);float spec=pow(max(dot(reflect(-sun,n),v),0.),120.);c+=vec3(1.,.91,.63)*spec*2.;float r=length(local.xz)/10.;float foam=smoothstep(.83,1.,r)*(.3+.7*pow(sin(w.x*4.+w.z*3.+t),2.));c=mix(c,vec3(.8,.9,.77),foam*.55);gl_FragColor=vec4(c,.90);\n#include <tonemapping_fragment>\n#include <colorspace_fragment>}`});const waterGeo=new T.CircleGeometry(10,72);waterGeo.rotateX(-Math.PI/2);const water=object(waterGeo,waterMaterial,-32,heightAt(-32,5)+.5,5,1,false);
 for(let i=0;i<30;i++){const theta=i/30*Math.PI*2,x=-32+Math.sin(theta)*10.1,z=5+Math.cos(theta)*10.1;object(rockGeo,stone,x,heightAt(x,z)-.4,z,.6+rand()*.7);}
 // Ruins, arches and broad stone stairs.
 const temporaryRuins=[];function ruin(x,z,angle=0){const g=new T.Group();g.position.set(x,heightAt(x,z),z);g.rotation.y=angle;for(const side of [-1,1]){for(let j=0;j<4;j++){const block=new T.Mesh(new T.BoxGeometry(.85,1.2,1.05),j%2?stone:ivory);block.position.set(side*2, .6+j*1.16,0);block.rotation.y=(rand()-.5)*.06;block.castShadow=block.receiveShadow=true;g.add(block);}const cap=new T.Mesh(new T.BoxGeometry(1.25,.35,1.35),ivory);cap.position.set(side*2,4.7,0);cap.castShadow=true;g.add(cap);}const arch=new T.Mesh(new T.TorusGeometry(2,.44,8,24,Math.PI),ivory);arch.position.y=4.5;arch.castShadow=true;g.add(arch);scene.add(g);temporaryRuins.push(g);}ruin(4,20,.25);ruin(-25,-11,-.7);ruin(24,-18,.6);
 const beacons=[];for(let i=0;i<3;i++){const b=BEACONS[i],group=new T.Group();group.position.set(b.x,heightAt(b.x,b.z),b.z);for(let j=0;j<3;j++){const step=new T.Mesh(new T.CylinderGeometry(2.6-j*.5,2.7-j*.5,.3,12),stone);step.position.y=j*.3;step.receiveShadow=step.castShadow=true;group.add(step);}const base=new T.Mesh(new T.CylinderGeometry(.45,.65,2,8),ivory);base.position.y=1.7;base.castShadow=true;group.add(base);const orb=new T.Mesh(new T.OctahedronGeometry(.75,1),glow.clone());orb.position.y=3.3;group.add(orb);const ring=new T.Mesh(new T.TorusGeometry(1.2,.055,8,64),gold);ring.position.y=3.3;ring.rotation.x=.4;group.add(ring);const beam=new T.Mesh(new T.CylinderGeometry(.06,.8,32,20,1,true),new T.MeshBasicMaterial({color:0xffe3a3,transparent:true,opacity:.13,depthWrite:false,side:T.DoubleSide,blending:T.AdditiveBlending}));beam.position.y=19;group.add(beam);scene.add(group);beacons.push({group,orb,ring,beam,lit:false,...b});}
 // Wind current / collectible ring trail.
 const wind=new T.Group();wind.position.set(11,heightAt(11,12),12);for(let i=0;i<5;i++){const ring=new T.Mesh(new T.TorusGeometry(1.7,.025,6,50),new T.MeshBasicMaterial({color:0xe4efd0,transparent:true,opacity:.18,depthWrite:false}));ring.rotation.x=Math.PI/2;ring.position.y=i*1.6;wind.add(ring);}scene.add(wind);
 const motesGeo=new T.BufferGeometry(),motesPos=new Float32Array(220*3);for(let i=0;i<220;i++){motesPos.set([(rand()-.5)*90,2+rand()*14,(rand()-.5)*90],i*3);}motesGeo.setAttribute('position',new T.BufferAttribute(motesPos,3));const motes=new T.Points(motesGeo,new T.PointsMaterial({color:0xffe5a3,size:.055,transparent:true,opacity:.75,depthWrite:false}));scene.add(motes);
 const clouds=[];const cloudMat=new T.MeshBasicMaterial({color:0xf3eee0,transparent:true,opacity:.32,depthWrite:false});for(let i=0;i<18;i++){const cloud=object(new T.SphereGeometry(1,12,8),cloudMat,(rand()-.5)*310,55+rand()*30,(rand()-.5)*300,1,false);cloud.scale.set(12+rand()*25,1.2+rand()*2,5+rand()*7);clouds.push(cloud);}
 await Promise.all(textureTasks);onProgress(.22,'지형과 바람 준비 완료');
 const loader=new GLTFLoader(),assets={};const assetNames=['tooth-hero','cavity-monster','tooth-citadel','brush-turret','island-tree','ancient-arch','mossy-cliff'];let loaded=0;
 await Promise.all(assetNames.map(async name=>{const gltf=await loader.loadAsync('/assets/arcade-models/'+name+'.glb');const root=gltf.scene;const bounds=new T.Box3().setFromObject(root),size=bounds.getSize(new T.Vector3()),center=bounds.getCenter(new T.Vector3());root.position.sub(center);root.position.y+=size.y/2;const normalized=new T.Group();normalized.add(root);normalized.scale.setScalar(1/size.y);normalized.traverse(o=>{if(o.isMesh){o.castShadow=o.receiveShadow=true;o.material.side=T.FrontSide;o.material.envMapIntensity=.55;o.material.roughness=Math.max(.5,o.material.roughness||.5);}});assets[name]=normalized;onProgress(.22+(++loaded/assetNames.length)*.73,`${loaded} / ${assetNames.length} 캐릭터와 유적 준비 완료`);}));

 // Replace the layout stand-ins with authored, textured environmental meshes.
 const forestTrees=low?trees.filter((_,i)=>i%2===0):trees;const oak=assets['island-tree'];oak.updateMatrixWorld(true);
 oak.traverse(o=>{if(!o.isMesh)return;const geometry=o.geometry.clone().applyMatrix4(o.matrixWorld);const material=o.material.clone();material.side=T.DoubleSide;const forest=new T.InstancedMesh(geometry,material,forestTrees.length),ot=new T.Object3D();
 forestTrees.forEach((tree,i)=>{const height=8+(i%5)*.65;ot.position.copy(tree.position);ot.rotation.set(0,i*2.39,0);ot.scale.setScalar(height);ot.updateMatrix();forest.setMatrixAt(i,ot.matrix);});forest.castShadow=forest.receiveShadow=true;scene.add(forest);});
 for(const o of temporaryRuins){scene.remove(o);const arch=assets['ancient-arch'].clone(true);arch.scale.multiplyScalar(6.4);arch.position.copy(o.position);arch.rotation.copy(o.rotation);scene.add(arch);}
 // Tall geological silhouettes flank the playable valley and shape the approach to its ruins.
 for(let i=0;i<15;i++){const x=(i%2?1:-1)*(33+(i%3)*5),z=-35+Math.floor(i/2)*11;const cliff=assets['mossy-cliff'].clone(true);cliff.scale.multiplyScalar(7+(i%4)*1.5);cliff.position.set(x,heightAt(x,z)-1,z);cliff.rotation.y=i*1.7;scene.add(cliff);rigid.push({x,z,r:2.4});}
 const citadel=assets['tooth-citadel'].clone(true);citadel.scale.multiplyScalar(14);citadel.position.set(GATE.x,heightAt(GATE.x,GATE.z),GATE.z);scene.add(citadel);rigid.push({x:GATE.x,z:GATE.z,r:6.3});
 const guardian=assets['brush-turret'].clone(true);guardian.scale.multiplyScalar(2);guardian.position.set(5,heightAt(5,26),26);scene.add(guardian);
 function instantiate(name,height=2){const root=assets[name].clone(true);root.scale.multiplyScalar(height);return root;}
 function update(t){clock.value=t;for(const b of beacons){b.orb.rotation.y=t*.5;b.orb.position.y=3.3+Math.sin(t*1.8)*.16;b.ring.rotation.z=t*.22;b.beam.material.opacity=b.lit?.20:.08;b.orb.material.emissiveIntensity=b.lit?3:.5;b.beam.visible=true;}for(let i=0;i<wind.children.length;i++)wind.children[i].position.y=(t*1.5+i*1.6)%8;clouds.forEach((c,i)=>{c.position.x+=.003*(1+i%3);if(c.position.x>170)c.position.x=-170;});motes.rotation.y=t*.005;}
 return {scene,sun,ground,water,beacons,rigid,instantiate,wind,update,grass,trees,assets,env};
}
