-- 0013_price_items_seed.sql
-- 초기 시드(정적 pricing.html 에서 바이트 동일 추출, 87행: 항목 71 + 그룹 16). 전부 공개(1).
-- 주의: price_items 가 비어있는 상태에서 1회만 실행할 것(다중행 INSERT). 코드측 시더는 COUNT>0 가드가 있어 중복 없음.
INSERT INTO price_items (tab, sort_order, kind, group_key, name, price, note, group_html, is_published) VALUES
('implant', 0, 'group', '임플란트', '', '', '', '<tr><td colspan="3" style="background:var(--gray-50);font-weight:700;color:var(--brand-dark);"><i class="fas fa-tooth" style="margin-right:6px;color:var(--brand);"></i> 임플란트</td></tr>', 1),
('implant', 1, 'item', '임플란트', '치과임플란트(1치당) — 스트라우만 / BLX <span class="popular-badge">프리미엄</span>', '<span class="price">160만원</span> <span class="price-won">(1,600,000원)</span>', '스위스 정품 픽스처', '', 1),
('implant', 2, 'item', '임플란트', '치과임플란트(1치당) — 오스템 / SOI', '<span class="price">100만원</span> <span class="price-won">(1,000,000원)</span>', '국산 프리미엄', '', 1),
('implant', 3, 'item', '임플란트', '치과임플란트(1치당) — 오스템 / CA', '<span class="price">80만원</span> <span class="price-won">(800,000원)</span>', '국산 표준', '', 1),
('implant', 4, 'item', '임플란트', '비절개 / 네비게이션 임플란트 수술', '<span class="price">10~30만원</span>', '추가 비용', '', 1),
('implant', 5, 'group', '골이식', '', '', '', '<tr><td colspan="3" style="background:var(--gray-50);font-weight:700;color:var(--brand-dark);"><i class="fas fa-bone" style="margin-right:6px;color:var(--brand);"></i> 골이식</td></tr>', 1),
('implant', 6, 'item', '골이식', '단순 골이식', '<span class="price">30만원</span>', '', '', 1),
('implant', 7, 'item', '골이식', '복잡 골이식', '<span class="price">50만원</span>', '', '', 1),
('implant', 8, 'item', '골이식', '단순 상악동 거상술', '<span class="price">50만원</span>', '', '', 1),
('implant', 9, 'item', '골이식', '복잡 상악동 거상술', '<span class="price">100만원</span>', '', '', 1),
('implant', 10, 'group', '마취', '', '', '', '<tr><td colspan="3" style="background:var(--gray-50);font-weight:700;color:var(--brand-dark);"><i class="fas fa-bed" style="margin-right:6px;color:var(--brand);"></i> 마취</td></tr>', 1),
('implant', 11, 'item', '마취', '수면마취', '<span class="price">20만원</span>', '', '', 1),
('prosthetic', 12, 'group', '인레이 / 크라운', '', '', '', '<tr><td colspan="3" style="background:var(--gray-50);font-weight:700;color:var(--brand-dark);"><i class="fas fa-crown" style="margin-right:6px;color:var(--brand);"></i> 인레이 / 크라운</td></tr>', 1),
('prosthetic', 13, 'item', '인레이 / 크라운', '세라믹 인레이 (치아당)', '<span class="price">35만원</span> <span class="price-won">(350,000원)</span>', '', '', 1),
('prosthetic', 14, 'item', '인레이 / 크라운', '지르코니아 크라운 (치아당)', '<span class="price">55만원</span> <span class="price-won">(550,000원)</span>', '', '', 1),
('prosthetic', 15, 'group', '글로우네이트 HOT', '', '', '', '<tr><td colspan="3" style="background:var(--gray-50);font-weight:700;color:var(--brand-dark);"><i class="fas fa-star" style="margin-right:6px;color:var(--brand);"></i> 글로우네이트 <span class="popular-badge">HOT</span></td></tr>', 1),
('prosthetic', 16, 'item', '글로우네이트 HOT', '글로우네이트 프리미엄 <span class="popular-badge">BEST</span>', '<span class="price">80만원</span>', '1본 기준', '', 1),
('prosthetic', 17, 'item', '글로우네이트 HOT', '글로우네이트 리페어 (타치과 재제작)', '<span class="price">상담 후 안내</span>', '기존 라미네이트 상태에 따라', '', 1),
('prosthetic', 18, 'group', '레진 (충치)', '', '', '', '<tr><td colspan="3" style="background:var(--gray-50);font-weight:700;color:var(--brand-dark);"><i class="fas fa-fill-drip" style="margin-right:6px;color:var(--brand);"></i> 레진 (충치)</td></tr>', 1),
('prosthetic', 19, 'item', '레진 (충치)', '뺨측, 어금니 씹는면 (좁은 부위)', '<span class="price">10만원</span>', '', '', 1),
('prosthetic', 20, 'item', '레진 (충치)', '뺨측, 어금니 씹는면 (넓은 부위)', '<span class="price">25만원</span>', '', '', 1),
('prosthetic', 21, 'item', '레진 (충치)', '치아사이 충치', '<span class="price">25만원</span>', '면당', '', 1),
('prosthetic', 22, 'item', '레진 (충치)', '앞니 뒷면 충치', '<span class="price">5만원</span>', '치아당', '', 1),
('prosthetic', 23, 'item', '레진 (충치)', '열린 옆면 충치', '<span class="price">7만원</span>', '치아당', '', 1),
('prosthetic', 24, 'item', '레진 (충치)', '치아 목 부위 충치', '<span class="price">10만원</span>', '치아당', '', 1),
('prosthetic', 25, 'item', '레진 (충치)', '치아 목 부위 페임', '<span class="price">7만원</span>', '치아당', '', 1),
('prosthetic', 26, 'group', '레진 (파절/심미)', '', '', '', '<tr><td colspan="3" style="background:var(--gray-50);font-weight:700;color:var(--brand-dark);"><i class="fas fa-magic" style="margin-right:6px;color:var(--brand);"></i> 레진 (파절/심미)</td></tr>', 1),
('prosthetic', 27, 'item', '레진 (파절/심미)', '앞니 파절 (협소한 파절)', '<span class="price">12만원</span>', '', '', 1),
('prosthetic', 28, 'item', '레진 (파절/심미)', '앞니 파절 (중간파절 / 중앙선 미달)', '<span class="price">30만원</span>', '', '', 1),
('prosthetic', 29, 'item', '레진 (파절/심미)', '앞니 파절 (중간파절 / 현정민 원장) <span class="popular-badge">PREMIUM</span>', '<span class="price">45만원</span>', '', '', 1),
('prosthetic', 30, 'item', '레진 (파절/심미)', '앞니 파절 (큰파절 / 중앙선 초과)', '<span class="price">50만원</span>', '', '', 1),
('prosthetic', 31, 'item', '레진 (파절/심미)', '앞니 파절 (큰파절 / 현정민 원장) <span class="popular-badge">PREMIUM</span>', '<span class="price">70만원</span>', '', '', 1),
('prosthetic', 32, 'item', '레진 (파절/심미)', '다이아스테마', '<span class="price">30만원</span>', '면당', '', 1),
('prosthetic', 33, 'item', '레진 (파절/심미)', '다이아스테마 (현정민 원장)', '<span class="price">50만원</span>', '', '', 1),
('prosthetic', 34, 'item', '레진 (파절/심미)', '블랙트라이앵글', '<span class="price">25만원</span>', '면당', '', 1),
('prosthetic', 35, 'item', '레진 (파절/심미)', '반점치 (좁은부위 / 점형태)', '<span class="price">20만원</span>', '', '', 1),
('prosthetic', 36, 'item', '레진 (파절/심미)', '반점치 (넓은 부위 / 면형태)', '<span class="price">30만원</span>', '', '', 1),
('denture', 37, 'group', '틀니', '', '', '', '<tr><td colspan="3" style="background:var(--gray-50);font-weight:700;color:var(--brand-dark);"><i class="fas fa-teeth-open" style="margin-right:6px;color:var(--brand);"></i> 틀니</td></tr>', 1),
('denture', 38, 'item', '틀니', '부분틀니', '<span class="price">150만원</span>', '악당 기준', '', 1),
('denture', 39, 'item', '틀니', '전체틀니', '<span class="price">150만원</span>', '악당 기준', '', 1),
('denture', 40, 'item', '틀니', '임플란트 틀니', '<span class="price">200만원</span>', '시술비 별도', '', 1),
('denture', 41, 'item', '틀니', '플리퍼', '<span class="price">10만원</span>', '악당 기준', '', 1),
('denture', 42, 'item', '틀니', '임시 틀니', '<span class="price">30만원</span>', '', '', 1),
('denture', 43, 'group', '기타 일반', '', '', '', '<tr><td colspan="3" style="background:var(--gray-50);font-weight:700;color:var(--brand-dark);"><i class="fas fa-stethoscope" style="margin-right:6px;color:var(--brand);"></i> 기타 일반</td></tr>', 1),
('denture', 44, 'item', '기타 일반', '레진 코어', '<span class="price">5만원</span>', '신경치료 후', '', 1),
('denture', 45, 'item', '기타 일반', '포스트', '<span class="price">10만원</span>', '신경치료 후 기둥', '', 1),
('denture', 46, 'item', '기타 일반', '비보험 스케일링 (치석제거)', '<span class="price">6만원</span> <span class="price-won">(60,000원)</span>', '보험 적용 시 약 1.5~2만원 (연 1회, 만 19세↑)', '', 1),
('denture', 47, 'item', '기타 일반', '치아미백 — 소프트 블리칭 (1회 30분)', '<span class="price">4.9만원</span> <span class="price-won">(49,000원)</span>', '부가세 10% 별도', '', 1),
('denture', 48, 'item', '기타 일반', '치아미백 — 하드 블리칭 (2회 60분)', '<span class="price">8만원</span> <span class="price-won">(80,000원)</span>', '부가세 10% 별도', '', 1),
('denture', 49, 'item', '기타 일반', '이갈이 장치', '<span class="price">100만원</span>', '', '', 1),
('denture', 50, 'item', '기타 일반', '턱보톡스', '<span class="price">7만원</span>', '미용목적시 부가세 별도', '', 1),
('ortho', 51, 'group', '인비절라인', '', '', '', '<tr><td colspan="3" style="background:var(--gray-50);font-weight:700;color:var(--brand-dark);"><i class="fas fa-teeth" style="margin-right:6px;color:var(--brand);"></i> 인비절라인</td></tr>', 1),
('ortho', 52, 'item', '인비절라인', '퍼스트', '<span class="price">400만원</span>', '', '', 1),
('ortho', 53, 'item', '인비절라인', '익스프레스', '<span class="price">300만원</span>', '', '', 1),
('ortho', 54, 'item', '인비절라인', '라이트', '<span class="price">450만원</span>', '', '', 1),
('ortho', 55, 'item', '인비절라인', '모더레이트 <span class="popular-badge">인기</span>', '<span class="price">550만원</span>', '', '', 1),
('ortho', 56, 'item', '인비절라인', '컴프레시브 <span class="popular-badge">전체교정</span>', '<span class="price">700만원</span>', '', '', 1),
('ortho', 57, 'group', '전체 장치', '', '', '', '<tr><td colspan="3" style="background:var(--gray-50);font-weight:700;color:var(--brand-dark);"><i class="fas fa-brackets-curly" style="margin-right:6px;color:var(--brand);"></i> 전체 장치</td></tr>', 1),
('ortho', 58, 'item', '전체 장치', '클리피씨', '<span class="price">500만원</span>', '', '', 1),
('ortho', 59, 'item', '전체 장치', '클라리티 울트라', '<span class="price">550만원</span>', '', '', 1),
('ortho', 60, 'group', '교정 보조', '', '', '', '<tr><td colspan="3" style="background:var(--gray-50);font-weight:700;color:var(--brand-dark);"><i class="fas fa-cog" style="margin-right:6px;color:var(--brand);"></i> 교정 보조</td></tr>', 1),
('ortho', 61, 'item', '교정 보조', '악궁 확장장치 (소아 / 어른)', '<span class="price">50 / 70만원</span>', '', '', 1),
('ortho', 62, 'item', '교정 보조', '악정형치료 (페이스마스크 / 헤드기어 등)', '<span class="price">200만원</span>', '', '', 1),
('ortho', 63, 'item', '교정 보조', 'ROA, ABP', '<span class="price">70만원</span>', '장치당', '', 1),
('ortho', 64, 'group', '제거 / 유지', '', '', '', '<tr><td colspan="3" style="background:var(--gray-50);font-weight:700;color:var(--brand-dark);"><i class="fas fa-undo" style="margin-right:6px;color:var(--brand);"></i> 제거 / 유지</td></tr>', 1),
('ortho', 65, 'item', '제거 / 유지', '본원 제거 (양악 / 편악)', '<span class="price">50 / 25만원</span>', '', '', 1),
('ortho', 66, 'item', '제거 / 유지', '타원 제거 (양악 / 편악)', '<span class="price">80 / 40만원</span>', '', '', 1),
('ortho', 67, 'item', '제거 / 유지', '유지장치 (양악 / 편악)', '<span class="price">50 / 25만원</span>', '', '', 1),
('ortho', 68, 'item', '제거 / 유지', 'Wrap around / 고정식(Fixed)', '<span class="price">30 / 15만원</span>', '', '', 1),
('ortho', 69, 'group', '사후 / 관리', '', '', '', '<tr><td colspan="3" style="background:var(--gray-50);font-weight:700;color:var(--brand-dark);"><i class="fas fa-wrench" style="margin-right:6px;color:var(--brand);"></i> 사후 / 관리</td></tr>', 1),
('ortho', 70, 'item', '사후 / 관리', '본원 제거 후 재부착', '<span class="price">5만원</span>', '', '', 1),
('ortho', 71, 'item', '사후 / 관리', '타치과 고정식 유지장치 수리', '<span class="price">3만원</span>', '치아당', '', 1),
('ortho', 72, 'item', '사후 / 관리', '타치과 와이어 찔림 처리', '<span class="price">2만원</span>', '', '', 1),
('ortho', 73, 'item', '사후 / 관리', '타치과 브라켓 탈락 재부착', '<span class="price">5만원</span>', '', '', 1),
('ortho', 74, 'item', '사후 / 관리', '매복치 견인 수술', '<span class="price">30만원</span>', '', '', 1),
('ortho', 75, 'item', '사후 / 관리', '치료종료 1년후 검진', '<span class="price">3만원</span>', '', '', 1),
('pediatric', 76, 'group', '소아 레진', '', '', '', '<tr><td colspan="3" style="background:var(--gray-50);font-weight:700;color:var(--brand-dark);"><i class="fas fa-child" style="margin-right:6px;color:var(--brand);"></i> 소아 레진</td></tr>', 1),
('pediatric', 77, 'item', '소아 레진', '유치 레진 (1면 / 2면 / 3면)', '<span class="price">6 / 8 / 10만원</span>', '', '', 1),
('pediatric', 78, 'item', '소아 레진', '불소', '<span class="price">3만원</span>', '', '', 1),
('pediatric', 79, 'item', '소아 레진', '웃음가스 (비보험)', '<span class="price">1만원</span>', '', '', 1),
('pediatric', 80, 'item', '소아 레진', '수면마취', '<span class="price">10만원</span>', '', '', 1),
('pediatric', 81, 'item', '소아 레진', '치아견인', '<span class="price">30만원</span>', '', '', 1),
('pediatric', 82, 'group', '소아 진료', '', '', '', '<tr><td colspan="3" style="background:var(--gray-50);font-weight:700;color:var(--brand-dark);"><i class="fas fa-baby" style="margin-right:6px;color:var(--brand);"></i> 소아 진료</td></tr>', 1),
('pediatric', 83, 'item', '소아 진료', '데라칼', '<span class="price">10만원</span>', '', '', 1),
('pediatric', 84, 'item', '소아 진료', 'Nance holding arch / Lingual arch', '<span class="price">25 / 30만원</span>', '', '', 1),
('pediatric', 85, 'item', '소아 진료', 'SS Crown / Band(crown) & Loop', '<span class="price">11 / 20만원</span>', '', '', 1),
('pediatric', 86, 'item', '소아 진료', '할터만 장치 (편측 / 양측)', '<span class="price">70 / 100만원</span>', '', '', 1);
